### ISSUE TITLE
Upgrade to latest version of d2

### ISSUE THREAD

**Issue by carusogabriel** [Vaelatern/mdbook-d2-go#1]
Hello there 👋🏼 

There's a new version of d2 out (https://github.com/terrastruct/d2/releases/tag/v0.4.0) which contains Grid diagrams, a very useful way to document things.

It appears that we are using an older version: https://github.com/Vaelatern/mdbook-d2-go/blob/b43ded3aa7221c09f2c5f71a2d7355923f1e8871/go.mod#L9 

Thanks for considering upgrading this project!

**Comment by Vaelatern** [comment]
Done!
